# DATABASE_URL="postgresql://mainquestbot:postgrespw@localhost:5432/postgres_db"
version: '3.8'
services:
 db:
   container_name: postgres_container
   image: postgres
   environment:
     POSTGRES_DB: postgres_db
     POSTGRES_USER: mainquestbot
     POSTGRES_PASSWORD: postgrespw
     PGDATA: /var/lib/postgresql/data
   ports:
     - "5432:5432"
   volumes:
     - data:/var/lib/postgresql/data
# Uncomment to use pgadmin
 #pgadmin:
  # container_name: pgadmin4_container
   #image: dpage/pgadmin4:6.13
 #  environment:
  #   PGADMIN_DEFAULT_EMAIL: admin@admin.com
   #  PGADMIN_DEFAULT_PASSWORD: secret
  #  # PGADMIN_LISTEN_PORT: 80
   #ports:
   #  - "8080:80"
  # volumes:
     #- pgadmin-data:/var/lib/pgadmin

volumes:
 data:
 #pgadmin-data: