name: Node.js Package and Release

on:
  push:
    branches:
      - "master"

jobs:
  main:
   runs-on: ubuntu-latest
   steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Install Clean
      run: npm ci
    - name: Build
      run: npm run build:production
